# site settings
title: Kubo
subtitle: HOME
email: vuong200989@gmail.com
description: This is a site store my writeup for CTF exam <br /> . Also study and research
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city: Tp.HCM
state: 
zip_code: 
country: VietNam
phone: N/A

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:https://www.facebook.com/vuong.vo.963434
github_url:
gitlab_url: 
googleplus_url: https://plus.google.com/u/0/117756886422615270544
instagram_url: 
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/vuong200989

# build settings
markdown: kramdown

sass:
  style: compressed
